# Default values for kube-recycle-bin
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  # Global image registry override
  imageRegistry: ""

namespace:
  create: true
  name: krb-system

# Controller configuration
controller:
  enabled: true
  image:
    repository: wcrum/krb-controller
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"
  serviceAccount:
    create: true
    name: krb-controller
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  replicaCount: 1

# Webhook configuration
webhook:
  enabled: true
  image:
    repository: wcrum/krb-webhook
    pullPolicy: IfNotPresent
    tag: "latest"
  serviceAccount:
    create: true
    name: krb-webhook
  service:
    type: ClusterIP
    port: 443
    targetPort: 443
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  replicaCount: 1

# Server configuration
server:
  enabled: true
  image:
    repository: wcrum/krb-server
    pullPolicy: IfNotPresent
    tag: "latest"
  serviceAccount:
    create: true
    name: krb-server
  service:
    type: ClusterIP
    port: 80
    targetPort: 8080
  env:
    PORT: "8080"
    WEB_DIR: "/run/web"
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  replicaCount: 1

# CRDs configuration
crds:
  install: true

