{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "kube-recycle-bin.namespace" . }}
  labels:
    {{- include "kube-recycle-bin.labels" . | nindent 4 }}
{{- end }}

