{{- if .Values.webhook.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.webhook.serviceAccount.name }}
  namespace: {{ include "kube-recycle-bin.namespace" . }}
  labels:
    {{- include "kube-recycle-bin.webhook.labels" . | nindent 4 }}
{{- if .Values.webhook.serviceAccount.create }}
automountServiceAccountToken: true
{{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.webhook.serviceAccount.name }}
  labels:
    {{- include "kube-recycle-bin.webhook.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create"]
  - apiGroups: ["krb.wcrum.dev"]
    resources: ["recycleitems"]
    verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.webhook.serviceAccount.name }}
  labels:
    {{- include "kube-recycle-bin.webhook.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.webhook.serviceAccount.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.webhook.serviceAccount.name }}
    namespace: {{ include "kube-recycle-bin.namespace" . }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.webhook.serviceAccount.name }}
  namespace: {{ include "kube-recycle-bin.namespace" . }}
  labels:
    {{- include "kube-recycle-bin.webhook.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.webhook.replicaCount }}
  selector:
    matchLabels:
      {{- include "kube-recycle-bin.webhook.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kube-recycle-bin.webhook.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.webhook.serviceAccount.name }}
      containers:
        - name: krb-webhook
          image: {{ include "kube-recycle-bin.image" (dict "root" . "image" .Values.webhook.image) }}
          imagePullPolicy: {{ .Values.webhook.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.webhook.service.targetPort }}
          resources:
            {{- toYaml .Values.webhook.resources | nindent 12 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webhook.serviceAccount.name }}
  namespace: {{ include "kube-recycle-bin.namespace" . }}
  labels:
    {{- include "kube-recycle-bin.webhook.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "kube-recycle-bin.webhook.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.webhook.service.port }}
      targetPort: {{ .Values.webhook.service.targetPort }}
  type: {{ .Values.webhook.service.type }}
{{- end }}

