apiVersion: v1
kind: Namespace
metadata:
  name: krb-system

# krb-controller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: krb-controller
  namespace: krb-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: krb-controller
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["validatingwebhookconfigurations"]
    verbs: ["*"]
  - apiGroups: ["krb.wcrum.dev"]
    resources: ["recyclepolicies"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: krb-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: krb-controller
subjects:
  - kind: ServiceAccount
    name: krb-controller
    namespace: krb-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: krb-controller
  namespace: krb-system
spec:
  selector:
    matchLabels:
      app: krb-controller
  template:
    metadata:
      labels:
        app: krb-controller
    spec:
      serviceAccountName: krb-controller
      containers:
        - name: krb-controller
          image: wcrum/krb-controller:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"

# krb-webhook
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: krb-webhook
  namespace: krb-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: krb-webhook
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create"]
  - apiGroups: ["krb.wcrum.dev"]
    resources: ["recycleitems"]
    verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: krb-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: krb-webhook
subjects:
  - kind: ServiceAccount
    name: krb-webhook
    namespace: krb-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: krb-webhook
  namespace: krb-system
spec:
  selector:
    matchLabels:
      app: krb-webhook
  template:
    metadata:
      labels:
        app: krb-webhook
    spec:
      serviceAccountName: krb-webhook
      containers:
        - name: krb-webhook
          image: wcrum/krb-webhook:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          ports:
            - containerPort: 443

---
apiVersion: v1
kind: Service
metadata:
  name: krb-webhook
  namespace: krb-system
spec:
  selector:
    app: krb-webhook
  ports:
    - port: 443
      targetPort: 443
  type: ClusterIP

# krb-server
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: krb-server
  namespace: krb-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: krb-server
rules:
  - apiGroups: ["krb.wcrum.dev"]
    resources: ["recycleitems"]
    verbs: ["get", "list", "delete"]
  - apiGroups: ["krb.wcrum.dev"]
    resources: ["recyclepolicies"]
    verbs: ["get", "list", "create", "delete"]
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["create"]
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: krb-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: krb-server
subjects:
  - kind: ServiceAccount
    name: krb-server
    namespace: krb-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: krb-server
  namespace: krb-system
spec:
  selector:
    matchLabels:
      app: krb-server
  template:
    metadata:
      labels:
        app: krb-server
    spec:
      serviceAccountName: krb-server
      containers:
        - name: krb-server
          image: wcrum/krb-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: WEB_DIR
              value: "/run/web"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: krb-server
  namespace: krb-system
spec:
  selector:
    app: krb-server
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
